{% set name = "nir" %}
{% set version = "1.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nir-{{ version }}.tar.gz
  sha256: a34e702ae2dbbc86d006e7fa094c62706c2b1a11bbd704edfdb49802f14f90b6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - h5py

test:
  imports:
    - nir
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Neuromorphic Intermediate Representation
  license: BSD-3-Clause
  license_file: LICENSE
  home: https://github.com/neuromorphs/NIR

extra:
  recipe-maintainers:
    - Tobias-Fischer
